name: Deploy GitHub Pages from Subdirectory

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install and build client-side packages
        run: |
          cd site-vite-project
          npm install
          npm run build
          cd ..

      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./site-vite-project/dist

      - uses: actions/deploy-pages@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          source: ./site-vite-project/dist
          branch: gh-pages
